# Generated by Django 4.2.29 on 2026-04-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferred_theme',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark'), ('black_white', 'Black & White')], default='light', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
    ]
